Test failure

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -57,4 +57,8 @@ jobs:
 
     - name: Verify Flask app output
       run: |
-        curl -s ${{ env.SERVICE_URL }}
+        curl -s ${{ env.SERVICE_URLwqie }}
+        if [ $? -ne 0 ]; then
+          echo "Flask app is not reachable."
+          exit 1  # Fail the job if the service is not reachable
+        fi
